version: "3"

services:
  web:
    build: ./
    networks:
      - default
      - proxy
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - APP_URL=http://${DOMAIN}
      - SKIP_CHOWN=1
      - PUID=1000
      - WEBROOT=/var/www/html/public
    volumes:
      - ./:/var/www/html:Z

  mysql:
    image: zolotoykod/mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-library}
      - MYSQL_USER=${MYSQL_USER:-library}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}

volumes:
  mysql:
    driver: local

networks:
  proxy:
    external: true
